# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cpp_build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./build.sh
    - name: run tests
      run: cd build && ../cpp/run_all_tests.sh

  java_build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: cd java && mvn clean install -DskipTests
    - name: run tests
      run: cd java && mvn test
